/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
  _key: string;
}>;

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  type?: "Dev Log" | "Tutorial" | "Opinion" | "Update";
  excerpt: string;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: BlockContent;
  author: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  publishedAt: string;
  featured?: boolean;
  readingTime?: number;
  seoTitle?: string;
  seoDescription?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  avatar?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  build: Array<string>;
  socialLinks?: {
    github?: string;
    linkedin?: string;
    email?: string;
    instagram?: string;
    twitter?: string;
    facebook?: string;
  };
  techStack: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "techTag";
  }>;
  shortIntro: string;
  intro: string;
  links?: {
    github?: string;
    linkedin?: string;
    email?: string;
  };
};

export type TechTag = {
  _id: string;
  _type: "techTag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  category?: "Language" | "Framework" | "Library" | "Styling" | "UI" | "State" | "Database" | "Auth" | "Tooling" | "Infra" | "Testing" | "Other";
  icon?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  website?: string;
  description?: string;
  popularity?: number;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  index: string;
  smallIntro: string;
  description: string;
  techStack: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "techTag";
  }>;
  githubLink?: string;
  liveLink?: string;
  images: {
    desktop?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    tablet?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    mobile?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
  accent?: string;
  textLight?: string;
  textDark?: string;
  featured?: boolean;
  timeline?: string;
  publishedAt?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = BlockContent | BlogPost | Author | TechTag | Project | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: allBlogPostsQuery
// Query: *[_type == "blogPost"] | order(publishedAt desc) {    _id,    title,    "slug": slug.current,    type,    excerpt,    publishedAt,    featured,    readingTime,    coverImage{asset->,alt},    author->{      name,    },      body  }
export type AllBlogPostsQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  type: "Dev Log" | "Opinion" | "Tutorial" | "Update" | null;
  excerpt: string;
  publishedAt: string;
  featured: boolean | null;
  readingTime: number | null;
  coverImage: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    alt: string | null;
  };
  author: {
    name: string | null;
  };
  body: BlockContent | null;
}>;
// Variable: getPostBySlugQuery
// Query: *[_type == "blogPost" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    type,    excerpt,    publishedAt,    featured,    readingTime,    coverImage{asset->,alt},    author->{      name,    },      body  }
export type GetPostBySlugQueryResult = {
  _id: string;
  title: string;
  slug: string;
  type: "Dev Log" | "Opinion" | "Tutorial" | "Update" | null;
  excerpt: string;
  publishedAt: string;
  featured: boolean | null;
  readingTime: number | null;
  coverImage: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    alt: string | null;
  };
  author: {
    name: string | null;
  };
  body: BlockContent | null;
} | null;
// Variable: avatarQuery
// Query: *[_type == "author"] | order(_createdAt desc)[0] {  name,  alt,  shortIntro,  intro,  build,  techStack[]->{    title,    icon{asset->}  },  avatar }
export type AvatarQueryResult = {
  name: string | null;
  alt: null;
  shortIntro: string;
  intro: string;
  build: Array<string>;
  techStack: Array<{
    title: string;
    icon: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
    } | null;
  }>;
  avatar: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
} | null;
// Variable: getAuthorSocialLinksQuery
// Query: *[_type == "author"] | order(_createdAt desc)[0] {  socialLinks}
export type GetAuthorSocialLinksQueryResult = {
  socialLinks: {
    github?: string;
    linkedin?: string;
    email?: string;
    instagram?: string;
    twitter?: string;
    facebook?: string;
  } | null;
} | null;
// Variable: featuredProjectsQuery
// Query: *[_type == 'project' && featured == true] | order(index asc) {  title,  index,  description,  accent,    textDark,    textLight,  githubLink,  liveLink,   techStack[]->{title},  "desktopImg": images.desktop.asset->,  "mobileImg": images.mobile.asset->,  "tabletImg": images.tablet.asset->,   'desktopAlt':images.desktop.alt,   'mobileAlt':images.mobile.alt,   'tabletAlt':images.tablet.alt}
export type FeaturedProjectsQueryResult = Array<{
  title: string;
  index: string;
  description: string;
  accent: string | null;
  textDark: string | null;
  textLight: string | null;
  githubLink: string | null;
  liveLink: string | null;
  techStack: Array<{
    title: string;
  }>;
  desktopImg: {
    _id: string;
    _type: "sanity.imageAsset";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    metadata?: SanityImageMetadata;
    source?: SanityAssetSourceData;
  } | null;
  mobileImg: {
    _id: string;
    _type: "sanity.imageAsset";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    metadata?: SanityImageMetadata;
    source?: SanityAssetSourceData;
  } | null;
  tabletImg: {
    _id: string;
    _type: "sanity.imageAsset";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    metadata?: SanityImageMetadata;
    source?: SanityAssetSourceData;
  } | null;
  desktopAlt: string | null;
  mobileAlt: string | null;
  tabletAlt: string | null;
}>;
// Variable: getAllTechTagsQuery
// Query: *[    _type == "techTag" &&    count(*[_type == "project" && references(^._id)]) >= 1  ] | order(title asc) {    title,    icon{asset->}  }
export type GetAllTechTagsQueryResult = Array<{
  title: string;
  icon: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
  } | null;
}>;
// Variable: allProjectsQuery
// Query: *[_type == 'project' && count(techStack[_ref in *[_type == "techTag" && title in $tags]._id]) == count($tags)] | order(index asc) {  title,  index,  description,  accent,    textDark,    textLight,  githubLink,  liveLink,   techStack[]->{title},  "desktopImg": images.desktop.asset->,  "mobileImg": images.mobile.asset->,  "tabletImg": images.tablet.asset->,   'desktopAlt':images.desktop.alt,   'mobileAlt':images.mobile.alt,   'tabletAlt':images.tablet.alt}
export type AllProjectsQueryResult = Array<never>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"blogPost\"] | order(publishedAt desc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    type,\n    excerpt,\n    publishedAt,\n    featured,\n    readingTime,\n    coverImage{asset->,alt},\n    author->{\n      name,\n    },\n      body\n  }": AllBlogPostsQueryResult;
    "*[_type == \"blogPost\" && slug.current == $slug][0] {\n    _id,\n    title,\n    \"slug\": slug.current,\n    type,\n    excerpt,\n    publishedAt,\n    featured,\n    readingTime,\n    coverImage{asset->,alt},\n    author->{\n      name,\n    },\n      body\n  }": GetPostBySlugQueryResult;
    "*[_type == \"author\"] | order(_createdAt desc)[0] {\n  name,\n  alt,\n  shortIntro,\n  intro,\n  build,\n  techStack[]->{\n    title,\n    icon{asset->}\n  },\n  avatar \n}": AvatarQueryResult;
    "*[_type == \"author\"] | order(_createdAt desc)[0] {\n  socialLinks\n}": GetAuthorSocialLinksQueryResult;
    "\n  *[_type == 'project' && featured == true] | order(index asc) {\n  title,\n  index,\n  description,\n  accent,\n    textDark,\n    textLight,\n  githubLink,\n  liveLink,\n   techStack[]->{title},\n  \"desktopImg\": images.desktop.asset->,\n  \"mobileImg\": images.mobile.asset->,\n  \"tabletImg\": images.tablet.asset->,\n   'desktopAlt':images.desktop.alt,\n   'mobileAlt':images.mobile.alt,\n   'tabletAlt':images.tablet.alt\n}": FeaturedProjectsQueryResult;
    "\n  *[\n    _type == \"techTag\" &&\n    count(*[_type == \"project\" && references(^._id)]) >= 1\n  ] | order(title asc) {\n    title,\n    icon{asset->}\n  }\n": GetAllTechTagsQueryResult;
    "\n  *[_type == 'project' && count(techStack[_ref in *[_type == \"techTag\" && title in $tags]._id]) == count($tags)] | order(index asc) {\n  title,\n  index,\n  description,\n  accent,\n    textDark,\n    textLight,\n  githubLink,\n  liveLink,\n   techStack[]->{title},\n  \"desktopImg\": images.desktop.asset->,\n  \"mobileImg\": images.mobile.asset->,\n  \"tabletImg\": images.tablet.asset->,\n   'desktopAlt':images.desktop.alt,\n   'mobileAlt':images.mobile.alt,\n   'tabletAlt':images.tablet.alt\n}": AllProjectsQueryResult;
  }
}
