import type { Metadata } from "next";
import { sanityFetch, SanityLive } from "@/sanity/lib/live";
import NavBar from "../../../components/navigation/NavBar";
import { PageTransition } from "../../../components/navigation/PageTransition";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";
import { SplitText } from "gsap/SplitText";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import Footer from "../../../components/layout/Footer";
import { getAuthorSocialLinksQuery } from "@/sanity/lib/queries";
gsap.registerPlugin(useGSAP, ScrollTrigger, SplitText);
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data: socials } = await sanityFetch({ query: getAuthorSocialLinksQuery });
  return (
    <>
      <NavBar />
      <PageTransition>{children}</PageTransition>
      <Footer socialLinks={socials} />
      <SanityLive />
    </>
  );
}
